---
title: "Report"
author: "Team 4"
date: "11/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## Obtaining the data
Dataset cbb contains statistics for each team in seasons 2015-2019 combined. Dataset cbb[n] has statistics for each team for season n. Added the data for 2020 to cbb since it has not been added.
```{r messages=FALSE}
cbb <- read.csv("datasets/cbb.csv")
head(cbb)
cbb15 <- read.csv("datasets/cbb15.csv")
cbb16 <- read.csv("datasets/cbb16.csv")
cbb17 <- read.csv("datasets/cbb17.csv")
cbb18 <- read.csv("datasets/cbb18.csv")
cbb19 <- read.csv("datasets/cbb19.csv")
cbb20 <- read.csv("datasets/cbb20.csv")
head(cbb20)
# Added 2020 data to cbb.
cbb1 <- full_join(cbb, cbb20)
# Dropped rank column and added 2020 as year for 2020 data.
# I checked first before the join that cbb$YEAR had no NA's so that only 2020 data's year was being set.
cbb1 <- subset(cbb1, select = -c(RK))
cbb1$YEAR[is.na(cbb1$YEAR)] <- 2020
```

## Cleaning
TODO
```{r}
str(cbb20)
```

## Analysis 1
```{r}

```

## Analysis 2
```{r}

```

## Analysis 3
```{r}

```

## Analysis 4
```{r}

```

## Analysis 5
```{r}

```

## Analysis 6
```{r}

```
